### ISSUE TITLE
Error: Invalid formula: /opt/homebrew/Library/Taps/lajosdeme/homebrew-utils/xcclear.rb

### ISSUE THREAD

**Issue by paluch** [lajosdeme/xcclear#3]
> brew install lajosdeme/utils/xcclear

==> Tapping lajosdeme/utils
Cloning into '/opt/homebrew/Library/Taps/lajosdeme/homebrew-utils'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 25 (delta 7), reused 14 (delta 4), pack-reused 0
Receiving objects: 100% (25/25), 4.82 KiB | 4.82 MiB/s, done.
Resolving deltas: 100% (7/7), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/lajosdeme/homebrew-utils/xcclear.rb
xcclear: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the lajosdeme/utils tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/lajosdeme/homebrew-utils/xcclear.rb:7

Error: Cannot tap lajosdeme/utils: invalid syntax in tap!

**Comment by dawidow** [comment]
I have same problem ;/
